before:
  hooks:
    - go mod tidy
builds:
  - main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.ShortCommit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
      - -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
archives:
  - replacements:
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
